name: "Read package info"
description: "Extract package.json info, current NPM version and expose as env vars"

runs:
  using: "composite"
  steps:
    - uses: dcarbone/install-jq-action@v2

    - name: Read package.json
      shell: bash
      run: |
        echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
        echo "HAVE_COVERAGE_SCRIPT=$(jq 'has(\"scripts\") and .scripts.coverage != null' package.json)" >> $GITHUB_ENV
        echo "HAVE_VALIDATE_SCRIPT=$(jq 'has(\"scripts\") and .scripts.validate != null' package.json)" >> $GITHUB_ENV
        echo "HAVE_LINT_SCRIPT=$(jq 'has(\"scripts\") and .scripts.lint != null' package.json)" >> $GITHUB_ENV
        echo "HAVE_UNIT_TEST_SCRIPT=$(jq 'has(\"scripts\") and .scripts.test != null' package.json)" >> $GITHUB_ENV

    - name: Get npm version
      shell: bash
      run: |
        echo "NPM_VERSION=$(curl -s https://registry.npmjs.org/${PACKAGE_NAME} | jq -r '."dist-tags".latest')" >> $GITHUB_ENV